# Generated by Django 5.2 on 2025-04-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_details_static',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные автомобиля (статично)'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_fio_static',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО клиента (статично)'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_services_static',
            field=models.TextField(blank=True, null=True, verbose_name='Кастомные услуги (статично)'),
        ),
        migrations.AddField(
            model_name='order',
            name='services_static',
            field=models.TextField(blank=True, null=True, verbose_name='Услуги (статично)'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на момент заказа'),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.clientcar', verbose_name='Автомобиль клиента'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название типа услуги'),
        ),
    ]
