# Generated by Django 5.1.6 on 2026-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_order_car_details_static_order_client_fio_static_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="base_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=5,
                verbose_name="Базовое время (ч)",
            ),
        ),
    ]
