# Generated by Django 5.1.6 on 2026-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_remove_legacy_order_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcar",
            name="plate_country",
            field=models.CharField(
                choices=[
                    ("RU", "Россия"),
                    ("BY", "Беларусь"),
                    ("KZ", "Казахстан"),
                    ("UA", "Украина"),
                    ("UZ", "Узбекистан"),
                    ("MD", "Молдова"),
                    ("AM", "Армения"),
                    ("AZ", "Азербайджан"),
                    ("KG", "Кыргызстан"),
                    ("TJ", "Таджикистан"),
                    ("TM", "Туркменистан"),
                ],
                default="RU",
                max_length=2,
                verbose_name="Страна номера",
            ),
        ),
    ]
