# Generated by Django 5.1.6 on 2026-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_add_plate_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_country",
            field=models.CharField(
                choices=[
                    ("RU", "Россия"),
                    ("BY", "Беларусь"),
                    ("KZ", "Казахстан"),
                    ("UA", "Украина"),
                    ("UZ", "Узбекистан"),
                    ("MD", "Молдова"),
                    ("AM", "Армения"),
                    ("AZ", "Азербайджан"),
                    ("KG", "Кыргызстан"),
                    ("TJ", "Таджикистан"),
                    ("TM", "Туркменистан"),
                ],
                default="RU",
                max_length=2,
                verbose_name="Страна телефона",
            ),
        ),
    ]
