# Generated by Django 5.1.6 on 2026-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_add_action_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="details",
            field=models.JSONField(blank=True, null=True, verbose_name="Подробности"),
        ),
    ]
