# Generated by Django 5.1.6 on 2026-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_add_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="consent_marketing",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на получение рассылок"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="consent_personal_data",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на обработку персональных данных"
            ),
        ),
    ]
