# Generated by Django 5.1.6 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_add_client_consents"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Пробег (км)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mileage_change_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина изменения пробега"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mileage_prev",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Пробег до изменения (км)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="org_snapshot",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Снапшот данных организации"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Наличные"),
                    ("card", "Карта"),
                    ("transfer", "Безналичный перевод"),
                    ("mixed", "Смешанная"),
                ],
                max_length=20,
                null=True,
                verbose_name="Форма оплаты",
            ),
        ),
    ]
