# Generated by Django 5.1.6 on 2026-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_org_snapshot_payment_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="car_snapshot",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Снапшот автомобиля и клиента"
            ),
        ),
    ]
