# Generated by Django 5.1.6 on 2026-06-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_car_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                ("size_kb", models.PositiveIntegerField(verbose_name="Размер, КБ")),
            ],
            options={
                "verbose_name": "Резервная копия",
                "verbose_name_plural": "Резервные копии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Интервал автокопирования (дней)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки резервного копирования",
                "verbose_name_plural": "Настройки резервного копирования",
            },
        ),
    ]
