# Generated by Django 5.1.6 on 2026-06-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_backuplog_backupsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backupsettings",
            options={
                "verbose_name": "Настройки системы",
                "verbose_name_plural": "Настройки системы",
            },
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Europe/Kaliningrad", "Калининград (UTC+2)"),
                    ("Europe/Moscow", "Москва, Санкт-Петербург (UTC+3)"),
                    ("Europe/Samara", "Самара, Удмуртия (UTC+4)"),
                    ("Asia/Yekaterinburg", "Екатеринбург (UTC+5)"),
                    ("Asia/Omsk", "Омск (UTC+6)"),
                    ("Asia/Krasnoyarsk", "Красноярск (UTC+7)"),
                    ("Asia/Irkutsk", "Иркутск (UTC+8)"),
                    ("Asia/Yakutsk", "Якутск (UTC+9)"),
                    ("Asia/Vladivostok", "Владивосток (UTC+10)"),
                    ("Asia/Magadan", "Магадан (UTC+11)"),
                    ("Asia/Kamchatka", "Камчатка (UTC+12)"),
                ],
                default="Europe/Moscow",
                max_length=50,
                verbose_name="Часовой пояс",
            ),
        ),
    ]
