# Generated by Django 5.1.6 on 2026-05-11 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0003_service_base_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Артикул"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Производитель"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Расходники", "Расходники"),
                            ("Подвеска", "Подвеска"),
                            ("Двигатель", "Двигатель"),
                            ("Тормозная система", "Тормозная система"),
                            ("Кузов", "Кузов"),
                            ("Электрика", "Электрика"),
                            ("Трансмиссия", "Трансмиссия"),
                            ("Прочее", "Прочее"),
                        ],
                        default="Прочее",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
            ],
            options={
                "verbose_name": "Деталь",
                "verbose_name_plural": "Детали",
                "ordering": ["article"],
            },
        ),
        migrations.CreateModel(
            name="SupplyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата приёмки"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(max_length=255, verbose_name="Поставщик"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Примечание")),
            ],
            options={
                "verbose_name": "Документ прихода",
                "verbose_name_plural": "Документы прихода",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        max_digits=10,
                        verbose_name="Стоимость нормо-часа (руб.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сервиса",
                "verbose_name_plural": "Настройки сервиса",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Заказано"),
                            ("in_transit", "В пути"),
                            ("received", "Получено"),
                        ],
                        default="ordered",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="mainapp.order",
                        verbose_name="Заказ-наряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ поставщику",
                "verbose_name_plural": "Заказы поставщикам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rack", models.CharField(max_length=10, verbose_name="Стеллаж")),
                ("shelf", models.CharField(max_length=10, verbose_name="Полка")),
                ("cell", models.CharField(max_length=10, verbose_name="Ячейка")),
                (
                    "label",
                    models.CharField(blank=True, max_length=30, verbose_name="Адрес"),
                ),
            ],
            options={
                "verbose_name": "Место хранения",
                "verbose_name_plural": "Места хранения",
                "ordering": ["rack", "shelf", "cell"],
                "unique_together": {("rack", "shelf", "cell")},
            },
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена закупки"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.supplydocument",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка прихода",
                "verbose_name_plural": "Строки прихода",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Зарезервировано"),
                            ("issued", "Выдано"),
                            ("installed", "Установлено"),
                        ],
                        default="reserved",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена продажи за единицу",
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        max_digits=5,
                        verbose_name="Наценка (%)",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_parts",
                        to="mainapp.order",
                        verbose_name="Заказ-наряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь в заказ-наряде",
                "verbose_name_plural": "Детали в заказ-наряде",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_applied",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Часы"
                    ),
                ),
                (
                    "complexity_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Коэффициент сложности",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Итоговая цена",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_services",
                        to="mainapp.order",
                        verbose_name="Заказ-наряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга в заказ-наряде (нормо-часы)",
                "verbose_name_plural": "Услуги в заказ-наряде (нормо-часы)",
            },
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_qty",
                    models.IntegerField(default=0, verbose_name="Общее количество"),
                ),
                (
                    "reserved_qty",
                    models.IntegerField(default=0, verbose_name="Зарезервировано"),
                ),
                (
                    "min_qty",
                    models.IntegerField(default=1, verbose_name="Минимальный остаток"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_entries",
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_entries",
                        to="warehouse.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток на складе",
                "verbose_name_plural": "Остатки на складе",
                "unique_together": {("part", "location")},
            },
        ),
    ]
