# Generated by Django 5.1.6 on 2026-05-11 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактное лицо"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="part",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Примечание"),
        ),
        migrations.AddField(
            model_name="supplydocument",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_documents",
                to="warehouse.purchaseorder",
                verbose_name="Заказ поставщику",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("ordered", "Заказано"),
                    ("in_transit", "В пути"),
                    ("partial", "Частично получено"),
                    ("received", "Получено"),
                ],
                default="ordered",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Заказано")),
                (
                    "received_qty",
                    models.IntegerField(default=0, verbose_name="Получено"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.purchaseorder",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AddField(
            model_name="supplyitem",
            name="po_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_items",
                to="warehouse.purchaseorderitem",
                verbose_name="Позиция заказа",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="supplydocument",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
