# Generated by Django 5.1.6 on 2026-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_supplier_remove_purchaseorder_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="package_qty",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Штук в упаковке"
            ),
        ),
    ]
