# Generated by Django 5.1.6 on 2026-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0005_workorderpart_work_order_service_wop_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyitem",
            name="pkg_qty",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Штук в упаковке"
            ),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Цена закупки (за упаковку)",
            ),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество (штук)"),
        ),
    ]
