# Generated by Django 5.1.6 on 2026-05-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_remove_legacy_order_models"),
        ("warehouse", "0006_supplyitem_pkg_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderservice",
            name="hourly_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Нормо-час (снапшот)",
            ),
        ),
        migrations.AddField(
            model_name="workorderservice",
            name="service_name_snapshot",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название услуги (снапшот)"
            ),
        ),
        migrations.AlterField(
            model_name="workorderservice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.service",
                verbose_name="Услуга",
            ),
        ),
    ]
