# Generated by Django 5.1.6 on 2026-05-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_add_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="work_order",
        ),
    ]
