# Generated by Django 5.1.6 on 2026-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0010_remove_purchase_order_work_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("ordered", "Заказано"),
                    ("in_transit", "В пути"),
                    ("partial", "Частично получено"),
                    ("received", "Получено"),
                    ("cancelled", "Отменено"),
                    ("partial_cancelled", "Частично получено / Отменено"),
                ],
                default="ordered",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
