# Generated by Django 5.1.6 on 2026-05-22 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_add_cancelled_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата списания"
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="Причина")),
                ("comment", models.TextField(blank=True, verbose_name="Примечание")),
            ],
            options={
                "verbose_name": "Списание",
                "verbose_name_plural": "Списания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WriteOffItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.storagelocation",
                        verbose_name="Место хранения",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.part",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "write_off",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.writeoff",
                        verbose_name="Документ списания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция списания",
                "verbose_name_plural": "Позиции списания",
            },
        ),
    ]
