# Generated by Django 5.1.6 on 2026-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_add_writeoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="salary_coefficient",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=4,
                verbose_name="Коэффициент ЗП",
            ),
        ),
    ]
