# Generated by Django 5.1.6 on 2026-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0013_add_employee_salary_coefficient"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderserviceemployee",
            name="salary_coefficient_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="К. ЗП (снапшот)",
            ),
        ),
    ]
