# Generated by Django 5.1.6 on 2026-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0015_backfill_salary_coeff_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="default_markup",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Наценка по умолчанию (%)",
            ),
        ),
    ]
