# Generated by Django 5.1.6 on 2026-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0017_wop_sale_price_to_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderpart",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Итоговая цена продажи",
            ),
        ),
    ]
