# Generated by Django 5.1.6 on 2026-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0019_add_employee_phone_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpart",
            name="reserved_entries",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"entry_id": N, "qty": M}, ...]',
                verbose_name="Трекинг резерваций",
            ),
        ),
    ]
