# Generated by Django 5.1.6 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0020_add_workorderpart_reserved_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopsettings",
            name="inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="kpp",
            field=models.CharField(
                blank=True, max_length=9, verbose_name="КПП (для ООО/АО)"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="ogrn",
            field=models.CharField(
                blank=True, max_length=13, verbose_name="ОГРН (для ООО/АО)"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="ogrnip",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="ОГРНИП (для ИП)"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="org_address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="org_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email организации"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="org_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название организации / ФИО ИП"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="org_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Телефон организации"
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="org_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ИП", "ИП"),
                    ("ООО", "ООО"),
                    ("АО", "АО"),
                    ("ПАО", "ПАО"),
                    ("ЗАО", "ЗАО"),
                ],
                default="ИП",
                max_length=10,
                verbose_name="Форма организации",
            ),
        ),
        migrations.AddField(
            model_name="workshopsettings",
            name="warranty_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Срок гарантии (дней)"
            ),
        ),
    ]
