# Generated by Django 5.1.6 on 2026-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0021_org_snapshot_payment_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpart",
            name="part_article_snapshot",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Артикул (снапшот)"
            ),
        ),
        migrations.AddField(
            model_name="workorderpart",
            name="part_name_snapshot",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название детали (снапшот)"
            ),
        ),
    ]
