# Generated by Django 5.1.6 on 2026-05-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0022_part_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderpart",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.part",
                verbose_name="Деталь",
            ),
        ),
    ]
