# Generated by Django 5.1.6 on 2026-05-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0023_wop_part_set_null"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workorderserviceemployee",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workorderserviceemployee",
            name="employee_name_snapshot",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ФИО сотрудника (снапшот)"
            ),
        ),
        migrations.AlterField(
            model_name="workorderserviceemployee",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="warehouse.employee",
                verbose_name="Сотрудник",
            ),
        ),
    ]
