# Generated by Django 5.1.6 on 2026-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0024_employee_set_null_name_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderpart",
            name="status",
            field=models.CharField(
                choices=[("reserved", "Зарезервировано"), ("cancelled", "Отменено")],
                default="reserved",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
